project:
  type: website

website:
  title: ""

  navbar:
    logo: image/LesRecetteduRoy1.png
    tools:
      - icon: github
        menu:
          - text: Report a Bug
            href:  https://bugs.com
            
    left:
      - text: Entrées
        href: recettes/entrees.qmd
        
      - text: Plats-Principaux
        href: recettes/plats-principaux.qmd
        
      - text: Desserts
        href: recettes/desserts.qmd
        
      - text: Collations
        href: recettes/collations.qmd
        
      - text: Déjeuners
        href: recettes/dejeuners.qmd

    right:
      - text: Infolettre
        href: recettes/infolettre.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full

editor: visual