project:
  type: website

website:
  title: ""

  navbar:
    logo: image/LesRecetteduRoy1.png
    tools:
      - icon: github
        menu:
          - text: Inspiration
            href: https://etienneplante17.github.io/pool_draft/
            
    left:
      - text: Entrées
        href: recettes/entrees.qmd
        
      - text: Plats-Principaux
        href: recettes/plats-principaux.qmd
        
      - text: Desserts
        href: recettes/desserts.qmd
        
      - text: Déjeuners
        href: recettes/dejeuners.qmd

    right:
      - text: Infolettre
        href: recettes/infolettre.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: false
    page-layout: full

editor: visual