---
title: "Muffins aux carottes de Xav"
author: "Xavier Roy"
categories:
  - Collation
---

# Ingrédients

**Secs**

 * 1 1/2 tasse de farine tout-usage ou au blé entier,
 * 1/2 tasse de flocons d'avoine,
 * 1 c. à thé de bicarbonate de soude,
 * 1/2 c. à thé de poudre à pâte,
 * 1 c. à thé de cannelle moulue,
 * 1/2 c. à thé de sel,
 
**Humides**

 * 2 tasses de carottes râpées,
 * 1/3 tasse d'huile végétale de saveur neutre, (*ex. de canola, d'avocat*)
 * 2/3 tasse de sirop d'érable ou Cassonde,
 * 3/4 tasse de yogourt nature ou à la vanille,
 * 2 oeufs,
 * 1 c. à thé d'extrait de vanille


**Exatrat**

 * 1 tasse de pacanes ou de noix de Grenoble hachées,
 * 1 tasse de caneberge

# Préparation

1. Préchauffer le four à 375°F.
2. Dans un grand bol, mélanger les ingrédients secs à l'aide d'une fourchette.
3. Au centre des ingrédients secs, ajouter les ingrédients humides (pas les carottes). Mélanger à la main avec la fourchette jusqu'à ce que les ingrédients secs et humides forment un mélange uniforme.
4. Ajouter les carottes râpées et les petits extras au choix. Mélanger une dernière fois.
5. Répartir la pâte dans 12 moules à muffins.
6. Cuire au four de 20 à 25 minutes (vérifier après 20 minutes) ou jusqu'à ce que le bout d'un petit couteau coupant piqué au centre d'un muffin en ressorte propre.

